//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "execution")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    pub task_version_id: Uuid,
    pub executor_id: Uuid,
    pub elapsed: Json,
    pub messages: Vec<Json>,
    pub parameter: Json,
    pub output: Option<Json>,
    pub error: Option<Json>,
    pub usage: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::task::Entity",
        from = "Column::TaskId",
        to = "super::task::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Task,
    #[sea_orm(
        belongs_to = "super::task_version::Entity",
        from = "Column::TaskVersionId",
        to = "super::task_version::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaskVersion,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ExecutorId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Task.def()
    }
}

impl Related<super::task_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskVersion.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
