[workspace]
resolver = "2"

members = [
    "tokenspan-api",
    "tokenspan-extra",
    "tokenspan-macros",
    "tokenspan-utils",
    "tokenspan-sdk",
    "tokenspan-migrations"
]

[workspace.lints.clippy]
new_ret_no_self = "allow"