[workspace]
resolver = "2"

members = [
    "tokenspan-api",
    "tokenspan-cli",
    "tokenspan-extra",
    "tokenspan-macros",
    "tokenspan-sdk"]

[workspace.lints.clippy]
new_ret_no_self = "allow"
