# execute task
POST {{host}}/api/v1/tasks/execute
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "parameterId": "00000000-0000-0000-0000-000000000000",
  "taskVersionId": "2e48ccab-c9ce-4982-9af7-e69c2fa25680",
  "apiKeyId": "862c53e7-7c84-472c-92eb-26880ada7bd8",
  "variables": {
    "text": "She no went to the market."
  }
}