[package]
name = "tokenspan-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.14"
axum = { git = "https://github.com/linrium/axum", branch = "feat/support-custom-sse-event", features = ["ws"] }
axum-extra = { version = "0.9.0", features = ["typed-header"] }
axum-macros = "0.4.0"
tower-http = { version = "0.5.0", features = ["trace", "timeout", "cors"] }
async-graphql = { git = "https://github.com/linrium/async-graphql", branch = "support-axum-0.7-custom", features = ["tokio", "chrono", "dataloader", "tracing"] }
async-graphql-axum = { git = "https://github.com/linrium/async-graphql", branch = "support-axum-0.7-custom" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "9"
anyhow = "1.0.75"
thiserror = "1.0.50"
async-trait = "0.1.74"
chrono = { version = "0.4.31", features = ["serde"] }
ring = "0.17.5"
data-encoding = "2.4.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "ansi"] }
validator = { version = "0.16", features = ["derive"] }
mongodb = { version = "2.0", features = ["tokio-runtime"] }
bson = { version = "2.0", features = ["chrono-0_4"] }
futures = "0.3"
config = "0.13.1"
magic-crypt = "3.1.13"
async-openai = "0.17.1"
futures-util = "0.3.29"
dotenv = "0.15.0"
async-stream = "0.3.5"
bytes = { version = "1.5.0" }
openssl = { version = "0.10.59", features = ["vendored"] }
regex = "1.10.2"
redis = { version = "0.24.0", features = ["tokio-comp"] }

tokenspan-macros = { path = "../tokenspan-macros" }
tokenspan-extra = { path = "../tokenspan-extra" }

[lints]
workspace = true