[package]
name = "tokenspan_api"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6", features = [] }
tower-http = { version = "0.4.0", features = ["trace", "timeout", "cors"] }
async-graphql = { version = "6.0", features = ["tokio", "chrono", "dataloader", "tracing"] }
async-graphql-axum = "6.0"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.9" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "9"
anyhow = "1.0.75"
thiserror = "1.0.50"
async-trait = "0.1.74"
axum-macros = "0.3.8"
chrono = "0.4.31"
ring = "0.17.5"
data-encoding = "2.4.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
validator = { version = "0.16", features = ["derive"] }
openai_api_rust = "0.1.8"
tokenspan-macros = { path = "../tokenspan-macros" }
tokenspan-utils = { path = "../tokenspan-utils" }