[package]
name = "tokenspan-extra"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.75"
thiserror = "1.0.50"
chrono = { version = "0.4.31", features = ["serde"] }

[lints]
workspace = true
