[package]
name = "tokenspan-extra"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { version = "2.0", features = ["chrono-0_4"] }
serde = { version = "1.0", features = ["derive"] }

[lints]
workspace = true
