### Create api key
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation CreateApiKey($input: ApiKeyCreateInput!) {
  createApiKey(input: $input) {
    id
    name
    ownerId
    providerId
    createdAt
    updatedAt
    provider {
      id
      name
      slug
    }
    owner {
      id
      username
    }
  }
}

{
  "input": {
    "name": "test1",
    "key": "{{open_ai_key}}",
    "providerId": "364a976f-1a4c-4cfa-8df1-e6ed58fb5f2f"
  }
}

### Get api keys
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query ApiKeys {
  apiKeys {
    nodes {
      id
      name
      ownerId
      providerId
      createdAt
      updatedAt
      provider {
        id
        name
        slug
        createdAt
        updatedAt
      }
      owner {
        id
        email
        username
        role
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalNodes
  }
}

### Get api key by id
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query GetApiKey($id: ID!) {
  apiKey(id: $id) {
    id
    name
    hint
    ownerId
    providerId
    createdAt
    updatedAt
    provider {
      id
      name
      slug
    }
    owner {
      id
      username
    }
  }
}

{
  "id": "657d208932fc0103875d623c"
}