### Create api key
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation CreateApiKey($input: ApiKeyCreateInput!) {
  createApiKey(input: $input) {
    id
    name
    ownerId
    providerId
    createdAt
    updatedAt
    provider {
      id
      name
      slug
    }
    owner {
      id
      username
    }
  }
}

{
  "input": {
    "name": "test",
    "key": "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",
    "providerId": "657d6159bf39bd6478cc68f5"
  }
}

### Get api keys
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query ApiKeys {
  apiKeys {
    nodes {
      id
      name
      hint
      ownerId
      providerId
      createdAt
      updatedAt
      provider {
        id
        name
        slug
        createdAt
        updatedAt
      }
      owner {
        id
        email
        username
        role
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalNodes
  }
}

### Get api key by id
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query GetApiKey($id: ID!) {
  apiKey(id: $id) {
    id
    name
    hint
    ownerId
    providerId
    createdAt
    updatedAt
    provider {
      id
      name
      slug
    }
    owner {
      id
      username
    }
  }
}

{
  "id": "657d208932fc0103875d623c"
}