### Create api key
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation CreateApiKey($input: ApiKeyCreateInput!) {
  createApiKey(input: $input) {
    id
    name
    ownerId
    providerId
    createdAt
    updatedAt
    provider {
      id
      name
      slug
    }
    owner {
      id
      username
    }
  }
}

{
  "input": {
    "name": "test1",
    "key": "{{open_ai_key}}",
    "providerId": "9aed5051-6be5-400a-91ac-3eeec701ee8d"
  }
}

### Get api keys
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query ApiKeys {
  apiKeys {
    nodes {
      id
      name
      ownerId
      providerId
      createdAt
      updatedAt
      provider {
        id
        name
        slug
        createdAt
        updatedAt
      }
      owner {
        id
        email
        username
        role
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    totalNodes
  }
}

### Get api key by id
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query GetApiKey($id: ID!) {
  apiKey(id: $id) {
    id
    name
    ownerId
    providerId
    createdAt
    updatedAt
    provider {
      id
      name
      slug
    }
    owner {
      id
      username
    }
  }
}

{
  "id": "6a369d0c-2c1e-4e88-8936-b786c7176f80"
}

### Update api key
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation UpdateApiKey($updateApiKeyId: UUID!, $input: ApiKeyUpdateInput!) {
  updateApiKey(id: $updateApiKeyId, input: $input) {
    id
    name
  }
}

{
  "updateApiKeyId": "6a369d0c-2c1e-4e88-8936-b786c7176f80",
  "input": {
    "name": "test2"
  }
}

### Delete api key
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation DeleteApiKey($deleteApiKeyId: UUID!) {
  deleteApiKey(id: $deleteApiKeyId) {
    id
    name
  }
}

{
  "deleteApiKeyId": "6a369d0c-2c1e-4e88-8936-b786c7176f80"
}