### Create model
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation CreateModel($input: ModelCreateInput!) {
  createModel(input: $input) {
    id
    name
    description
    slug
    context
    inputPricing {
      price
      tokens
      currency
    }
    outputPricing {
      price
      tokens
      currency
    }
    trainingAt
    providerId
    createdAt
    updatedAt
  }
}

{
  "input": {
    "name": "gpt-3.5-turbo-1106",
    "description": "The latest GPT-3.5 Turbo model with improved instruction following, JSON mode, reproducible outputs, parallel function calling, and more. Returns a maximum of 4,096 output tokens.",
    "slug": "gpt-3.5-turbo-1106",
    "context": 16385,
    "inputPricing": {
      "price": 0.001,
      "currency": "USD",
      "tokens": 1000
    },
    "outputPricing": {
      "price": 0.002,
      "tokens": 1000,
      "currency": "USD"
    },
    "trainingAt": "2023-12-17T04:11:16.803571",
    "providerId": "07ff7c31-fedd-46fe-a3ce-157be3a8c3d7"
  }
}

### Get models
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query Models {
  models {
    nodes {
      id
      name
      description
      slug
      context
      inputPricing {
        price
        tokens
        currency
      }
      outputPricing {
        price
        tokens
        currency
      }
      trainingAt
      providerId
      createdAt
      updatedAt
    }
    totalNodes
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}

### Get model by id
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query Model($modelId: UUID!) {
  model(id: $modelId) {
    id
    name
    description
    slug
    context
    inputPricing {
      price
      tokens
      currency
    }
    outputPricing {
      price
      tokens
      currency
    }
    trainingAt
    providerId
    createdAt
    updatedAt
  }
}

{
  "modelId": "e8b9719a-4f05-499b-8776-c5a634b0b96b"
}

### Update model
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation UpdateModel($updateModelId: UUID!, $input: ModelUpdateInput!) {
  updateModel(id: $updateModelId, input: $input) {
    id
    name
    description
    slug
    context
    inputPricing {
      price
      tokens
      currency
    }
    outputPricing {
      price
      tokens
      currency
    }
    trainingAt
    providerId
    createdAt
    updatedAt
  }
}

{
  "updateModelId": "e8b9719a-4f05-499b-8776-c5a634b0b96b",
  "input": {
    "name": "test",
    "description": "Similar capabilities as text-davinci-003 but compatible with legacy Completions endpoint and not Chat Completions.",
    "slug": "gpt-3.5-turbo-instruct",
    "context": 4096,
    "inputPricing": {
      "price": 0.0016,
      "tokens": 1000,
      "currency": "USD"
    },
    "outputPricing": {
      "price": 0.0021,
      "tokens": 1000,
      "currency": "USD"
    }
  }
}

### Delete model
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation DeleteModel($deleteModelId: UUID!) {
  deleteModel(id: $deleteModelId) {
    id
    name
    description
    slug
    context
    inputPricing {
      price
      tokens
      currency
    }
    outputPricing {
      price
      tokens
      currency
    }
    trainingAt
    providerId
    createdAt
    updatedAt
  }
}

{
  "deleteModelId": "e8b9719a-4f05-499b-8776-c5a634b0b96b"
}