### Create provider
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation CreateProvider($input: ProviderCreateInput!) {
  createProvider(input: $input) {
    id
    name
    slug
    createdAt
    updatedAt
  }
}

{
  "input": {
    "name": "AWS",
    "slug": "aws"
  }
}

### Get providers
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query GetProviders {
  providers {
    edges {
      node {
        id
        name
        slug
        createdAt
        updatedAt
      }
      cursor
    }
    pageInfo {
      endCursor
      startCursor
      hasNextPage
      hasPreviousPage
    }
  }
}

### Update provider by id
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation UpdateProvider($id: UUID!, $input: ProviderUpdateInput!) {
  updateProvider(id: $id, input: $input) {
    id
    name
    slug
    createdAt
    updatedAt
  }
}

{
  "id": "c0660675-0b86-4bb2-aaed-f806e2823e2d",
  "input": {
    "slug": "zzz"
  }
}