### Update task version
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation UpdateTaskVersion($updateTaskVersionId: UUID!, $input: TaskVersionUpdateInput!) {
  updateTaskVersion(id: $updateTaskVersionId, input: $input) {
    id
    semver
    version
    releaseNote
    description
    document
    status
    taskId
    createdAt
    updatedAt
    messages {
      content
      raw
      role
    }
    parameters {
      id
      name
      temperature
      maxTokens
      stopSequences
      topP
      frequencyPenalty
      presencePenalty
      extra
      modelId
      model {
        id
        name
        description
        slug
        context
        trainingAt
        providerId
        createdAt
        updatedAt
      }
    }
  }
}

{
  "updateTaskVersionId": "2e48ccab-c9ce-4982-9af7-e69c2fa25680",
  "input": {
    "description": "test",
    "document": "test",
    "messages": [
      {
        "raw": "You will be provided with statements, and your task is to convert them to standard English.",
        "content": "You will be provided with statements, and your task is to convert them to standard English.",
        "role": "SYSTEM"
      },
      {
        "raw": null,
        "content": "<var name=\"text\"/>",
        "role": "USER"
      }
    ],
    "parameters": [
      {
        "name": "test",
        "temperature": 1,
        "maxTokens": 64,
        "stopSequences": [],
        "topP": 1,
        "frequencyPenalty": 0,
        "presencePenalty": 0,
        "extra": null,
        "modelId": "315b23e6-ee19-4161-b5d0-c93218a51b5e"
      }
    ]
  }
}