### Create task
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

mutation CreateTask($input: TaskCreateInput!) {
  createTask(input: $input) {
    id
    name
    slug
    createdAt
    updatedAt
    version {
      id
      version
      releaseNote
      description
      document
      status
      taskId
      createdAt
      updatedAt
    }
  }
}

{
  "input": {
    "name": "test 6",
    "private": false,
    "slug": "test",
    "modelId": "2d06e1d2-fbf0-497c-8ba9-9610802850df"
  }
}

### Get tasks
GRAPHQL {{host}}/graphql
Authorization: Bearer {{token}}

query Task {
  tasks {
    nodes {
      id
      name
      slug
      createdAt
      updatedAt
      version {
        id
        version
        semver
        releaseNote
        description
        document
        status
        taskId
        createdAt
        updatedAt
        parameters {
          id
          name
          temperature
          maxTokens
          stopSequences
          topP
          frequencyPenalty
          presencePenalty
          extra
          modelId
          createdAt
          updatedAt
          model {
            id
            name
            description
            slug
            context
            inputPricing {
              price
              tokens
              currency
            }
            outputPricing {
              price
              tokens
              currency
            }
            trainingAt
            providerId
            createdAt
            updatedAt
          }
        }
      }
    }
    totalNodes
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}