name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: tokenspan-upload
        cache-directories: "/home/runner/.cache/prisma/binaries/cli/4.8.0"
    - name: Generate Prisma
      run: cargo prisma generate --schema tokenspan-api/prisma/schema.prisma
    - name: Build
      run: cargo build --locked
    - name: Run tests
      run: cargo test
    - name: Run clippy
      run: cargo clippy
